CREATE EXTENSION IF NOT EXISTS "uuid-ossp";


--
-- Common Shared Data Model for awards
--

CREATE TABLE "identity" (
    "id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    "created" timestamptz NOT NULL DEFAULT current_timestamp,
    "updated" timestamptz NOT NULL DEFAULT current_timestamp,

    "type" text,

    "identity_id" text,
    "display_name" text,
    "display_affiliation" text,

    "access_token" text,
    "refresh_token" text,
    "access_scope" text,
    "access_token_expire" int,

    "groups" text[],

    "last_login_date" timestamptz,

    UNIQUE("type", "identity_id")
);


CREATE TABLE "file" (
    "id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    "created" timestamptz NOT NULL DEFAULT current_timestamp,
    "updated" timestamptz NOT NULL DEFAULT current_timestamp,

    "file_name" text,
    "file_display_name" text,
    "file_mime_type" text,
    "file_byte_size" int,

    "storage_type" text,
    "storage_key" text,

    "confirmed" boolean
);




-- Submission specific tables
--

CREATE TABLE "submission" (
    "id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    "created" timestamptz NOT NULL DEFAULT current_timestamp,
    "updated" timestamptz NOT NULL DEFAULT current_timestamp,

    "submitter_id" uuid REFERENCES "identity",
    "curator_id" uuid REFERENCES "identity",

    "submission_date" timestamptz,
    "publish_date" timestamptz,

    "title" text,
    "authors" JSONB,
    "pmr_workspace" text,

    "phase" text,

    "all_files_present" boolean,
    "results_match" boolean,
    "model_annotated" boolean,
    "curation_notes" text
);



CREATE TABLE "submission-article-files" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY,
    "submission_id" uuid REFERENCES "submission",
    "file_id" uuid REFERENCES "file",
    "order" int
);


