ALTER TABLE "submission"
    ADD COLUMN "primary_papers" JSONB,
    ADD COLUMN "keywords" JSONB,
    ADD COLUMN "kind" text,
    ADD COLUMN "price_acknowledged" boolean;


CREATE TABLE "submission-supplementary-files" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY,
    "submission_id" uuid REFERENCES "submission",
    "file_id" uuid REFERENCES "file",
    "order" int,
    "label" text
);


CREATE TABLE "submission-supplementary-data-files" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY,
    "submission_id" uuid REFERENCES "submission",
    "file_id" uuid REFERENCES "file",
    "order" int
);